import {useNavigate} from 'react-router-dom';import {Calculator,ShieldCheck,FileSpreadsheet,Mail,ReceiptText,Globe2,ArrowRight,Sparkles} from 'lucide-react';import {Card,PageHead,Pill} from '../../components/UI';
const pillars=[
 {n:'01',label:'RATING',title:'Instant Multi-Carrier Rating',text:'Normalize LTL carrier rates, customer pricing, transit and margin in Quote Studio.',path:'/quotes',icon:Calculator,status:'Live'},
 {n:'02',label:'MARGIN PROTECTION',title:'Rebill Prevention Guardrails',text:'Verified addresses, structured freight data, customer rules and freight-audit variance controls.',path:'/finance',icon:ShieldCheck,status:'Active'},
 {n:'03',label:'CONTRACTED RATES',title:'Tariff & Pricing Wizard',text:'Customer, lane, carrier, weight, class and minimum-margin pricing rules.',path:'/pricing',icon:FileSpreadsheet,status:'Active'},
 {n:'04',label:'ORDER ENTRY',title:'Email-to-Quote Automation',text:'Integration-ready intake architecture for turning customer email requests into quote drafts.',path:'/integrations',icon:Mail,status:'Adapter ready'},
 {n:'05',label:'ACCOUNTING',title:'Automated Freight Audit',text:'Compare carrier invoices to quoted cost, route exceptions, approve or dispute before AP.',path:'/finance',icon:ReceiptText,status:'Active'},
 {n:'06',label:'EXPERIENCE',title:'Branded Customer Portal',text:'Self-service quoting, booking, tracking, documents and invoice visibility over shared APIs.',path:'/portal-admin',icon:Globe2,status:'Foundation'},
];
export default function AutomationCenterPage(){const nav=useNavigate();return <><PageHead eyebrow="BUILT FOR LESS THAN TRUCKLOAD" title="Six Pillars of LTL Automation" sub="Rate faster, prevent rebills, protect margin and remove repetitive brokerage work without sacrificing operational control."/><div className="automationIntro"><Card className="automationCallout"><Sparkles/><span>VALHALLA AUTOMATION STACK</span><h2>One operating system from quote request to audited invoice.</h2><p>Every automation is built on the same normalized customer, carrier, quote, shipment and financial records.</p></Card><div className="automationChecklist"><div>✓ One-screen rating and normalized carrier options</div><div>✓ Address and shipment-data validation</div><div>✓ Customer pricing and minimum margin rules</div><div>✓ Carrier invoice audit against original quote</div></div></div><div className="pillarGrid">{pillars.map(p=><button className="pillarCard" onClick={()=>nav(p.path)} key={p.n}><div className="pillarNum">{p.n}</div><div className="pillarIcon"><p.icon/></div><div><span>{p.label}</span><h3>{p.title}</h3><p>{p.text}</p><b>Open workspace <ArrowRight/></b></div><Pill tone={p.status==='Live'||p.status==='Active'?'success':'info'}>{p.status}</Pill></button>)}</div></>}
