from datetime import datetime
from decimal import Decimal
from pydantic import BaseModel, Field, field_validator
from app.schemas.common import ORMModel
from app.domains.customers.utils import format_us_phone


class CustomerProfileInput(BaseModel):
    legal_name: str | None = None
    website: str | None = None
    phone: str | None = None
    account_manager: str | None = None
    sales_owner: str | None = None
    payment_terms: str = "Net 30"
    tax_exempt: bool = False
    credit_hold: bool = False
    onboarding_status: str = "active"
    preferred_contact_method: str = "email"
    billing_address: dict | None = None
    operating_preferences: dict = Field(default_factory=dict)

    @field_validator("phone")
    @classmethod
    def normalize_phone(cls, value):
        return format_us_phone(value)


class CustomerCreate(BaseModel):
    # Customer codes are generated by Valhalla Freight. Optional is retained for backwards-compatible imports.
    code: str | None = None
    name: str
    industry: str | None = None
    billing_email: str | None = None
    default_markup_pct: Decimal = Decimal("15")
    credit_limit: Decimal = Decimal("0")
    profile: CustomerProfileInput | None = None


class CustomerUpdate(BaseModel):
    name: str | None = None
    status: str | None = None
    industry: str | None = None
    billing_email: str | None = None
    default_markup_pct: Decimal | None = None
    credit_limit: Decimal | None = None
    profile: CustomerProfileInput | None = None


class CustomerSummary(ORMModel):
    id: int
    code: str
    name: str
    status: str
    industry: str | None = None
    billing_email: str | None = None
    default_markup_pct: Decimal
    credit_limit: Decimal
    location_count: int = 0
    contact_count: int = 0
    shipment_count: int = 0
    active_shipment_count: int = 0
    revenue_total: Decimal = Decimal("0")


class CustomerProfileOut(CustomerProfileInput, ORMModel):
    id: int
    customer_id: int
    created_at: datetime
    updated_at: datetime


class LocationCreate(BaseModel):
    name: str
    location_type: str = "shipping"
    address1: str
    address2: str | None = None
    city: str
    state: str
    postal_code: str
    country: str = "USA"
    contact_name: str | None = None
    phone: str | None = None
    email: str | None = None
    dock_hours: str | None = None
    appointment_required: bool = False
    liftgate_default: bool = False
    residential: bool = False
    limited_access: bool = False
    instructions: str | None = None


    @field_validator("phone")
    @classmethod
    def normalize_phone(cls, value):
        return format_us_phone(value)


class LocationOut(LocationCreate, ORMModel):
    id: int
    customer_id: int
    active: bool
    created_at: datetime


class ContactCreate(BaseModel):
    first_name: str
    last_name: str
    title: str | None = None
    email: str | None = None
    phone: str | None = None
    mobile: str | None = None
    role: str = "operations"
    primary: bool = False
    billing_contact: bool = False
    quote_contact: bool = False


    @field_validator("phone", "mobile")
    @classmethod
    def normalize_phones(cls, value):
        return format_us_phone(value)


class ContactOut(ContactCreate, ORMModel):
    id: int
    customer_id: int
    active: bool
    created_at: datetime


class ActivityCreate(BaseModel):
    activity_type: str = "note"
    subject: str
    body: str | None = None


class ActivityOut(ActivityCreate, ORMModel):
    id: int
    customer_id: int
    created_by: str | None = None
    created_at: datetime


class ShipmentMini(BaseModel):
    id: int
    shipment_number: str
    status: str
    origin: dict
    destination: dict
    carrier_id: int | None = None
    customer_charge: Decimal
    pickup_date: str | None = None


class Customer360(BaseModel):
    customer: CustomerSummary
    profile: CustomerProfileOut | None = None
    locations: list[LocationOut] = Field(default_factory=list)
    contacts: list[ContactOut] = Field(default_factory=list)
    activities: list[ActivityOut] = Field(default_factory=list)
    shipments: list[ShipmentMini] = Field(default_factory=list)
