import {useState} from 'react';
import {UserPlus,X} from 'lucide-react';
import {customerApi} from '../api';
import {formatUsPhone} from '../utils/formatters';
export default function ContactModal({customerId,close,saved}:{customerId:number,close:()=>void,saved:()=>void}){
 const [f,setF]=useState<any>({first_name:'',last_name:'',title:'',email:'',phone:'',mobile:'',role:'operations',primary:false,billing_contact:false,quote_contact:false}); const [saving,setSaving]=useState(false); const set=(k:string,v:any)=>setF((x:any)=>({...x,[k]:v}));
 async function submit(e:any){e.preventDefault();setSaving(true);try{await customerApi.addContact(customerId,f);saved()}finally{setSaving(false)}}
 return <div className="modalShade"><form className="entityModal compact" onSubmit={submit}><div className="entityModalHead"><div className="entityModalIcon"><UserPlus/></div><div><span>CUSTOMER 360</span><h2>Add customer contact</h2></div><button type="button" onClick={close}><X/></button></div><div className="entityFormGrid"><label>First name<input required value={f.first_name} onChange={e=>set('first_name',e.target.value)}/></label><label>Last name<input required value={f.last_name} onChange={e=>set('last_name',e.target.value)}/></label><label>Title<input value={f.title} onChange={e=>set('title',e.target.value)}/></label><label>Role<select value={f.role} onChange={e=>set('role',e.target.value)}><option value="operations">Operations</option><option value="billing">Billing</option><option value="executive">Executive</option><option value="shipping">Shipping</option><option value="receiving">Receiving</option></select></label><label>Email<input type="email" value={f.email} onChange={e=>set('email',e.target.value)} placeholder="name@customer.com"/></label><label>Phone<input value={f.phone} onChange={e=>set('phone',formatUsPhone(e.target.value))} placeholder="(913) 223-4045" inputMode="tel"/></label><label>Mobile<input value={f.mobile} onChange={e=>set('mobile',formatUsPhone(e.target.value))} placeholder="(913) 223-4045" inputMode="tel"/></label><div/><label className="checkLabel"><input type="checkbox" checked={f.primary} onChange={e=>set('primary',e.target.checked)}/>Primary contact</label><label className="checkLabel"><input type="checkbox" checked={f.billing_contact} onChange={e=>set('billing_contact',e.target.checked)}/>Billing contact</label><label className="checkLabel"><input type="checkbox" checked={f.quote_contact} onChange={e=>set('quote_contact',e.target.checked)}/>Quote contact</label></div><div className="entityModalFoot"><button type="button" className="btn secondary" onClick={close}>Cancel</button><button className="btn primary" disabled={saving}>{saving?'Saving...':'Save contact'}</button></div></form></div>
}
