import {useState} from 'react';
import {X,Building2,Hash,Phone,Mail,Globe2} from 'lucide-react';
import {customerApi} from '../api';
import type {CustomerSummary} from '../types';
import AddressField from './AddressField';
import {formatUsPhone} from '../utils/formatters';

export default function CustomerModal({onClose,onSaved}:{onClose:()=>void,onSaved:(c:CustomerSummary)=>void}){
 const [form,setForm]=useState({name:'',industry:'',billing_email:'',default_markup_pct:'15',credit_limit:'0',legal_name:'',website:'',phone:'',payment_terms:'Net 30',address1:'',address2:'',city:'',state:'',postal_code:'',country:'USA'}); const [saving,setSaving]=useState(false),[error,setError]=useState('');
 const set=(k:string,v:any)=>setForm(f=>({...f,[k]:v}));
 const patchAddress=(p:any)=>setForm(f=>({...f,...p}));
 async function save(e:any){e.preventDefault();setSaving(true);setError('');try{const c=await customerApi.create({name:form.name,industry:form.industry||null,billing_email:form.billing_email||null,default_markup_pct:form.default_markup_pct,credit_limit:form.credit_limit,profile:{legal_name:form.legal_name||form.name,website:form.website||null,phone:form.phone||null,payment_terms:form.payment_terms,billing_address:{address1:form.address1,address2:form.address2||'',city:form.city,state:form.state,postal_code:form.postal_code,country:form.country}}});onSaved(c)}catch(err:any){setError(err?.message||'Unable to create customer')}finally{setSaving(false)}}
 return <div className="modalShade"><form className="entityModal customerCreateModal" onSubmit={save}><div className="entityModalHead"><div className="entityModalIcon"><Building2/></div><div><span>CUSTOMER 360</span><h2>Create customer account</h2></div><button type="button" onClick={onClose}><X/></button></div>
 <div className="autoCodeBanner"><Hash size={16}/><div><b>Customer code generated automatically</b><span>Valhalla Freight assigns the next permanent customer code when the account is created.</span></div></div>
 <div className="entityFormGrid"><label>Display name<input required value={form.name} onChange={e=>set('name',e.target.value)} placeholder="Acme Industrial"/></label><label>Industry<input value={form.industry} onChange={e=>set('industry',e.target.value)} placeholder="Manufacturing"/></label><label className="wide">Legal name<input value={form.legal_name} onChange={e=>set('legal_name',e.target.value)} placeholder="Acme Industrial Manufacturing, Inc."/></label><label><span className="labelWithIcon"><Phone size={11}/>Phone</span><input value={form.phone} onChange={e=>set('phone',formatUsPhone(e.target.value))} placeholder="(913) 223-4045" inputMode="tel"/></label><label><span className="labelWithIcon"><Mail size={11}/>Billing email</span><input type="email" value={form.billing_email} onChange={e=>set('billing_email',e.target.value)} placeholder="ap@customer.com"/></label><label><span className="labelWithIcon"><Globe2 size={11}/>Website</span><input value={form.website} onChange={e=>set('website',e.target.value)} placeholder="customer.com"/></label><label>Default markup %<input type="number" step=".01" value={form.default_markup_pct} onChange={e=>set('default_markup_pct',e.target.value)}/></label>
 <div className="formSectionLabel wide"><span>Primary / billing address</span><small>This address is saved to the customer account and can be used throughout Valhalla Freight.</small></div>
 <label className="wide">Street address<AddressField required value={form.address1} onValueChange={v=>set('address1',v)} onAddressSelected={patchAddress} placeholder="Start typing the customer address…"/></label><label className="wide">Suite / Building / Address 2<input value={form.address2} onChange={e=>set('address2',e.target.value)} placeholder="Suite 200"/></label><label>City<input required value={form.city} onChange={e=>set('city',e.target.value)}/></label><label>State<input required maxLength={3} value={form.state} onChange={e=>set('state',e.target.value.toUpperCase())}/></label><label>ZIP<input required value={form.postal_code} onChange={e=>set('postal_code',e.target.value)}/></label><label>Country<input required value={form.country} onChange={e=>set('country',e.target.value)}/></label>
 <label>Credit limit<input type="number" step=".01" value={form.credit_limit} onChange={e=>set('credit_limit',e.target.value)}/></label><label>Payment terms<select value={form.payment_terms} onChange={e=>set('payment_terms',e.target.value)}><option>Prepaid</option><option>Net 15</option><option>Net 30</option><option>Net 45</option><option>Net 60</option></select></label></div>
 {error&&<div className="formError">{error}</div>}<div className="entityModalFoot"><button type="button" className="btn secondary" onClick={onClose}>Cancel</button><button className="btn primary" disabled={saving}>{saving?'Creating...':'Create customer'}</button></div></form></div>
}
