import {useState} from 'react';
import {useNavigate,useParams} from 'react-router-dom';
import {ArrowLeft,Building2,MapPin,Users,WalletCards,Activity,Truck,Plus,Mail,Phone,Globe2,Clock3,ShieldCheck,CreditCard,StickyNote,Warehouse,CheckCircle2,AlertTriangle} from 'lucide-react';
import {Card,Pill} from '../../../components/UI';
import {useCustomer360} from '../useCustomer360';
import CustomerNotes from './CustomerNotes';
import LocationModal from './LocationModal';
import ContactModal from './ContactModal';
import NoteModal from './NoteModal';
import {telHref,websiteHref} from '../utils/formatters';

const tabs=[['overview','Overview',Building2],['locations','Locations',MapPin],['contacts','Contacts',Users],['notes','Notes',StickyNote],['commercial','Commercial',WalletCards],['activity','Activity',Activity]] as const;

export default function CustomerDetail(){
 const {customerId}=useParams(); const id=Number(customerId); const nav=useNavigate(); const {data,loading,error,refresh}=useCustomer360(id); const [tab,setTab]=useState<(typeof tabs)[number][0]>('overview'); const [modal,setModal]=useState<'location'|'contact'|'note'|null>(null);
 if(loading) return <div className="customerDetailLoading">Loading Customer 360…</div>;
 if(error||!data) return <div className="customerDetailLoading">{error||'Customer not found.'}</div>;
 const c=data.customer,p=data.profile; const gp=(Number(c.revenue_total||0)*Number(c.default_markup_pct||0)/(100+Number(c.default_markup_pct||0)));
 return <>
  <div className="customer360Head"><button className="backLink" onClick={()=>nav('/customers')}><ArrowLeft size={15}/>Customers</button><div className="customer360Title"><div className="customerHeroAvatar">{c.name.slice(0,2).toUpperCase()}</div><div><div className="customerHeroMeta"><span>{c.code}</span><Pill tone={c.status==='active'?'success':'neutral'}>{c.status}</Pill>{p?.credit_hold&&<Pill tone="warning">Credit hold</Pill>}</div><h1>{c.name}</h1><p>{p?.legal_name||c.industry||'Customer account'}</p></div></div><div className="customer360Actions"><button className="btn secondary" onClick={()=>setModal('note')}><StickyNote size={15}/>Add note</button><button className="btn primary" onClick={()=>nav('/quotes')}><Plus size={15}/>New quote</button></div></div>
  <div className="customer360Kpis"><Metric label="Active shipments" value={String(c.active_shipment_count)} note={`${c.shipment_count} total shipments`} icon={<Truck/>}/><Metric label="Recorded revenue" value={`$${Number(c.revenue_total||0).toLocaleString(undefined,{maximumFractionDigits:0})}`} note={`Est. GP $${gp.toLocaleString(undefined,{maximumFractionDigits:0})}`} icon={<WalletCards/>}/><Metric label="Locations" value={String(c.location_count)} note="Operational shipping sites" icon={<MapPin/>}/><Metric label="Contacts" value={String(c.contact_count)} note="Customer stakeholders" icon={<Users/>}/></div>
  <div className="customerTabs">{tabs.map(([key,label,Icon])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}><Icon size={15}/>{label}</button>)}</div>
  {tab==='overview'&&<Overview data={data}/>} {tab==='locations'&&<Locations data={data} add={()=>setModal('location')}/>} {tab==='contacts'&&<Contacts data={data} add={()=>setModal('contact')}/>} {tab==='notes'&&<CustomerNotes data={data} add={()=>setModal('note')}/>} {tab==='commercial'&&<Commercial data={data}/>} {tab==='activity'&&<ActivityTab data={data}/>} 
  {modal==='location'&&<LocationModal customerId={id} close={()=>setModal(null)} saved={()=>{setModal(null);refresh()}}/>}{modal==='contact'&&<ContactModal customerId={id} close={()=>setModal(null)} saved={()=>{setModal(null);refresh()}}/>}{modal==='note'&&<NoteModal customerId={id} close={()=>setModal(null)} saved={()=>{setModal(null);refresh()}}/>}
 </>
}
function Metric({label,value,note,icon}:{label:string,value:string,note:string,icon:any}){return <Card className="customer360Metric"><div className="customerMetricIcon">{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{note}</small></div></Card>}
function Overview({data}:{data:any}){const c=data.customer,p=data.profile,primary=data.contacts.find((x:any)=>x.primary),bill=p?.billing_address;return <div className="customer360Grid"><div className="customer360Main"><Card><SectionHead title="Account profile" sub="Core commercial and operating identity"/><div className="infoGrid"><Info label="Legal name" value={p?.legal_name||'—'}/><Info label="Industry" value={c.industry||'—'}/><Info label="Website" value={p?.website||'—'} icon={<Globe2/>} href={p?.website?websiteHref(p.website):undefined} external/><Info label="Main phone" value={p?.phone||'—'} icon={<Phone/>} href={p?.phone?telHref(p.phone):undefined}/><Info label="Billing email" value={c.billing_email||'—'} icon={<Mail/>} href={c.billing_email?`mailto:${c.billing_email}`:undefined}/><Info label="Payment terms" value={p?.payment_terms||'Net 30'} icon={<CreditCard/>}/></div></Card><Card><SectionHead title="Recent shipment activity" sub="Latest operational freight tied to this account"/>{data.shipments.length?<div className="shipmentMiniList">{data.shipments.map((s:any)=><div className="shipmentMini" key={s.id}><div><b>{s.shipment_number}</b><span>{s.origin?.city}, {s.origin?.state} → {s.destination?.city}, {s.destination?.state}</span></div><div><strong>${Number(s.customer_charge).toLocaleString(undefined,{minimumFractionDigits:2})}</strong><Pill tone="info">{s.status}</Pill></div></div>)}</div>:<div className="emptyCompact">No shipments have been booked for this customer yet.</div>}</Card></div><div className="customer360Side"><Card><SectionHead title="Account ownership"/><Info label="Account manager" value={p?.account_manager||'Unassigned'}/><Info label="Sales owner" value={p?.sales_owner||'Unassigned'}/><Info label="Onboarding" value={p?.onboarding_status||'active'}/></Card><Card><SectionHead title="Primary contact"/>{primary?<div className="primaryContact"><div className="contactAvatar">{primary.first_name[0]}{primary.last_name[0]}</div><b>{primary.first_name} {primary.last_name}</b><span>{primary.title||primary.role}</span>{primary.email&&<a href={`mailto:${primary.email}`}><Mail size={13}/>{primary.email}</a>}{primary.phone&&<a href={telHref(primary.phone)}><Phone size={13}/>{primary.phone}</a>}</div>:<div className="emptyCompact">No primary contact assigned.</div>}</Card><Card><SectionHead title="Billing address"/>{bill?<div className="billingAddress"><MapPin size={16}/><div><b>{bill.address1}</b><span>{bill.city}, {bill.state} {bill.postal_code}</span><span>{bill.country||'USA'}</span></div></div>:<div className="emptyCompact">No billing address on file.</div>}</Card></div></div>}
function Locations({data,add}:{data:any,add:()=>void}){return <Card><SectionHead title="Customer locations" sub="Origins, destinations, plants, warehouses and distribution facilities" action={<button className="btn primary" onClick={add}><Plus size={14}/>Add location</button>}/><div className="locationGrid">{data.locations.map((l:any)=><div className="locationCard" key={l.id}><div className="locationIcon"><Warehouse/></div><div className="locationBody"><div className="locationTitle"><div><b>{l.name}</b><span>{l.location_type}</span></div><Pill tone={l.active?'success':'neutral'}>{l.active?'Active':'Inactive'}</Pill></div><p>{l.address1}{l.address2?`, ${l.address2}`:''}<br/>{l.city}, {l.state} {l.postal_code}</p><div className="locationFlags">{l.appointment_required&&<span><Clock3/>Appointment</span>}{l.liftgate_default&&<span>Liftgate</span>}{l.limited_access&&<span>Limited access</span>}{l.residential&&<span>Residential</span>}</div>{l.dock_hours&&<small>Dock hours: {l.dock_hours}</small>}</div></div>)}</div></Card>}
function Contacts({data,add}:{data:any,add:()=>void}){return <Card><SectionHead title="Customer contacts" sub="Operations, billing, executive and quoting stakeholders" action={<button className="btn primary" onClick={add}><Plus size={14}/>Add contact</button>}/><div className="contactGrid">{data.contacts.map((x:any)=><div className="contactCard" key={x.id}><div className="contactAvatar lg2">{x.first_name[0]}{x.last_name[0]}</div><div className="contactBody"><div><b>{x.first_name} {x.last_name}</b>{x.primary&&<Pill tone="success">Primary</Pill>}</div><span>{x.title||x.role}</span>{x.email&&<a href={`mailto:${x.email}`}><Mail size={13}/>{x.email}</a>}{x.phone&&<a href={telHref(x.phone)}><Phone size={13}/>{x.phone}</a>}<div className="contactTags">{x.billing_contact&&<em>Billing</em>}{x.quote_contact&&<em>Quotes</em>}<em>{x.role}</em></div></div></div>)}</div></Card>}
function Commercial({data}:{data:any}){const c=data.customer,p=data.profile;return <div className="commercialGrid"><Card><SectionHead title="Pricing profile" sub="Default commercial rules used when no more specific pricing rule matches"/><div className="commercialHero"><div><span>Default markup</span><strong>{Number(c.default_markup_pct).toFixed(2)}%</strong></div><div><span>Credit limit</span><strong>${Number(c.credit_limit).toLocaleString()}</strong></div></div><div className="commercialRows"><Info label="Payment terms" value={p?.payment_terms||'Net 30'}/><Info label="Tax exempt" value={p?.tax_exempt?'Yes':'No'}/><Info label="Preferred contact" value={p?.preferred_contact_method||'Email'}/></div></Card><Card><SectionHead title="Credit & account controls"/><div className={`creditState ${p?.credit_hold?'hold':'clear'}`}>{p?.credit_hold?<AlertTriangle/>:<CheckCircle2/>}<div><b>{p?.credit_hold?'Credit hold active':'Account clear to transact'}</b><span>{p?.credit_hold?'Quotes can be reviewed but booking should require approval.':'No current customer-level credit restrictions.'}</span></div></div><div className="policyBox"><ShieldCheck/><div><b>Commercial control architecture</b><span>Customer defaults feed the pricing engine, while lane/carrier-specific rules can override them by priority.</span></div></div></Card></div>}
function ActivityTab({data}:{data:any}){const events=data.activities.filter((a:any)=>a.activity_type!=='note');return <Card><SectionHead title="Account activity" sub="System events and customer relationship history. Notes have their own dedicated workspace."/>{events.length?<div className="activityTimeline">{events.map((a:any)=><div className="activityRow" key={a.id}><div className="activityDot"/><div><div className="activityMeta"><b>{a.subject}</b><span>{new Date(a.created_at).toLocaleString()}</span></div>{a.body&&<p>{a.body}</p>}<small>{a.created_by||'Valhalla Freight'} · {a.activity_type}</small></div></div>)}</div>:<div className="activityEmpty"><Activity size={24}/><b>No non-note activity yet</b><span>Quotes, shipments, invoices, calls and system events will appear here as those workflows are connected.</span></div>}</Card>}
function SectionHead({title,sub,action}:{title:string,sub?:string,action?:any}){return <div className="sectionHead"><div><h3>{title}</h3>{sub&&<p>{sub}</p>}</div>{action}</div>}
function Info({label,value,icon,href,external}:{label:string,value:string,icon?:any,href?:string,external?:boolean}){return <div className="infoItem"><span>{label}</span><div>{icon}{href?<a className="infoLink" href={href} target={external?'_blank':undefined} rel={external?'noreferrer':undefined}>{value}</a>:value}</div></div>}
