import {useState} from 'react';
import {MapPin,X} from 'lucide-react';
import {customerApi} from '../api';
import AddressField from './AddressField';
import {formatUsPhone} from '../utils/formatters';

export default function LocationModal({customerId,close,saved}:{customerId:number,close:()=>void,saved:()=>void}){
 const [f,setF]=useState<any>({name:'',location_type:'shipping',address1:'',address2:'',city:'',state:'',postal_code:'',country:'USA',phone:'',email:'',dock_hours:'',appointment_required:false,liftgate_default:false,residential:false,limited_access:false,instructions:''}); const [saving,setSaving]=useState(false);
 const set=(k:string,v:any)=>setF((x:any)=>({...x,[k]:v})); const patch=(p:any)=>setF((x:any)=>({...x,...p}));
 async function submit(e:any){e.preventDefault();setSaving(true);try{await customerApi.addLocation(customerId,f);saved()}finally{setSaving(false)}}
 return <div className="modalShade"><form className="entityModal locationModal" onSubmit={submit}><div className="entityModalHead"><div className="entityModalIcon"><MapPin/></div><div><span>CUSTOMER 360</span><h2>Add customer location</h2></div><button type="button" onClick={close}><X/></button></div><div className="entityFormGrid">
  <label>Location name<input required value={f.name} onChange={e=>set('name',e.target.value)} placeholder="Kansas City Distribution Center"/></label><label>Type<select value={f.location_type} onChange={e=>set('location_type',e.target.value)}><option value="shipping">Shipping</option><option value="plant">Plant</option><option value="warehouse">Warehouse</option><option value="distribution">Distribution</option><option value="office">Office</option></select></label>
  <label className="wide">Street address<AddressField required value={f.address1} onValueChange={v=>set('address1',v)} onAddressSelected={patch} placeholder="Start typing the street address…"/></label><label className="wide">Suite / Building / Address 2<input value={f.address2} onChange={e=>set('address2',e.target.value)} placeholder="Suite 200"/></label><label>City<input required value={f.city} onChange={e=>set('city',e.target.value)}/></label><label>State<input required value={f.state} onChange={e=>set('state',e.target.value.toUpperCase())} maxLength={3}/></label><label>ZIP<input required value={f.postal_code} onChange={e=>set('postal_code',e.target.value)}/></label><label>Country<input value={f.country} onChange={e=>set('country',e.target.value)}/></label>
  <label>Location phone<input value={f.phone} onChange={e=>set('phone',formatUsPhone(e.target.value))} placeholder="(913) 223-4045"/></label><label>Location email<input type="email" value={f.email} onChange={e=>set('email',e.target.value)} placeholder="shipping@customer.com"/></label><label>Dock hours<input value={f.dock_hours} onChange={e=>set('dock_hours',e.target.value)} placeholder="Mon-Fri 07:00-16:00"/></label>
  <label className="checkLabel"><input type="checkbox" checked={f.appointment_required} onChange={e=>set('appointment_required',e.target.checked)}/>Appointment required</label><label className="checkLabel"><input type="checkbox" checked={f.liftgate_default} onChange={e=>set('liftgate_default',e.target.checked)}/>Liftgate default</label><label className="checkLabel"><input type="checkbox" checked={f.residential} onChange={e=>set('residential',e.target.checked)}/>Residential</label><label className="checkLabel"><input type="checkbox" checked={f.limited_access} onChange={e=>set('limited_access',e.target.checked)}/>Limited access</label><label className="wide">Special instructions<textarea rows={4} value={f.instructions} onChange={e=>set('instructions',e.target.value)} placeholder="Gate instructions, dock requirements, check-in process…"/></label>
 </div><div className="entityModalFoot"><button type="button" className="btn secondary" onClick={close}>Cancel</button><button className="btn primary" disabled={saving}>{saving?'Saving...':'Save location'}</button></div></form></div>
}
