import {useEffect,useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {MapPin,Truck,ArrowLeft} from 'lucide-react';
import {api} from '../../services/api';
import {Card,PageHead} from '../../components/UI';
import {customerApi} from '../customers/api';
import type {CustomerSummary} from '../customers/types';
import LaneAddressSelector,{emptyLaneAddress,useCustomerLocations,LocationsLoading,type LaneAddress} from '../../shared/freight/LaneAddressSelector';
import FreightDetailsFields from '../../shared/freight/FreightDetailsFields';

type Carrier={id:number;name:string;scac:string;active:boolean};
export default function CreateShipmentPage(){
 const nav=useNavigate();const [customers,setCustomers]=useState<CustomerSummary[]>([]),[carriers,setCarriers]=useState<Carrier[]>([]),[customerId,setCustomerId]=useState<number|''>(''),[carrierId,setCarrierId]=useState<number|''>(''),[origin,setOrigin]=useState<LaneAddress>(emptyLaneAddress()),[destination,setDestination]=useState<LaneAddress>(emptyLaneAddress()),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const {locations,loading}=useCustomerLocations(customerId);
 useEffect(()=>{customerApi.list().then(x=>{setCustomers(x);if(x.length)setCustomerId(x[0].id)});api<Carrier[]>('/carriers').then(x=>{const active=x.filter(c=>c.active);setCarriers(active);if(active.length)setCarrierId(active[0].id)})},[]);
 useEffect(()=>{setOrigin(emptyLaneAddress());setDestination(emptyLaneAddress())},[customerId]);
 async function create(e:any){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError('');try{const s:any=await api('/shipments/direct',{method:'POST',body:JSON.stringify({customer_id:Number(customerId),carrier_id:Number(carrierId),pickup_date:f.get('pickup_date')||null,origin:{...origin,address2:origin.address2||null,country:origin.country==='USA'?'US':origin.country},destination:{...destination,address2:destination.address2||null,country:destination.country==='USA'?'US':destination.country},handling_units:[{quantity:Number(f.get('qty')),type:'Pallet',weight_lbs:Number(f.get('weight')),length_in:Number(f.get('length')),width_in:Number(f.get('width')),height_in:Number(f.get('height')),freight_class:String(f.get('class'))}],accessorials:[]})});nav(`/shipments/${s.id}`)}catch(err:any){setError(err.message||'Unable to create shipment')}finally{setBusy(false)}}
 return <><PageHead eyebrow="OPERATIONS / DIRECT BOOKING" title="Create Shipment" sub="Use this path when the carrier is already known. Valhalla Freight rates only the selected carrier, creates the audit quote record, and moves the load directly into the Shipment Control Tower." actions={<button className="btn secondary" onClick={()=>nav('/shipments')}><ArrowLeft size={14}/>Shipments</button>}/><Card className="directShipmentCard"><form onSubmit={create}><div className="sectiontitle"><Truck/><div><h3>Customer & carrier</h3><p>Choose the customer and the carrier they have instructed you to use.</p></div></div><div className="form2"><label>Customer<select required value={customerId} onChange={e=>setCustomerId(Number(e.target.value))}>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Carrier<select required value={carrierId} onChange={e=>setCarrierId(Number(e.target.value))}>{carriers.map(c=><option key={c.id} value={c.id}>{c.name} ({c.scac})</option>)}</select></label></div>{loading&&<LocationsLoading/>}<div className="sectiontitle top"><MapPin/><div><h3>Lane information</h3><p>Saved locations and Google-verified one-off addresses are both available.</p></div></div><div className="form2 quoteLaneGrid"><LaneAddressSelector title="ORIGIN" address={origin} setAddress={setOrigin} locations={locations}/><LaneAddressSelector title="DESTINATION" address={destination} setAddress={setDestination} locations={locations}/></div><FreightDetailsFields/><div className="sectiontitle top"><Truck/><div><h3>Pickup</h3><p>Requested pickup date for the operational shipment.</p></div></div><div className="form2 directPickup"><label>Pickup date<input type="date" name="pickup_date"/></label></div>{error&&<div className="inlineError">{error}</div>}<button className="btn primary wide" disabled={busy||!customerId||!carrierId}><Truck size={16}/>{busy?'Creating shipment...':'Rate selected carrier & create shipment'}</button></form></Card></>
}
