import {useEffect,useState} from 'react';
import {ArrowLeft,MapPin,Truck,ReceiptText,Clock3,Package,Building2} from 'lucide-react';
import {Link,useParams} from 'react-router-dom';
import {Card,Pill} from '../../components/UI';
import {shipmentApi} from './api';
import type {ShipmentDetail} from './types';
const money=(v:any)=>`$${Number(v||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const title=(s:string)=>s.replaceAll('_',' ').replace(/\b\w/g,x=>x.toUpperCase());
export default function ShipmentDetailPage(){const {shipmentId}=useParams();const [s,setS]=useState<ShipmentDetail|null>(null);useEffect(()=>{if(shipmentId)shipmentApi.detail(Number(shipmentId)).then(setS)},[shipmentId]);if(!s)return <div className="customerDetailLoading">Loading shipment record…</div>;const actual=s.final_carrier_cost??s.carrier_cost;const gp=Number(s.customer_charge)-Number(actual);return <>
 <div className="shipmentDetailHead"><Link to="/shipments" className="backLink"><ArrowLeft size={14}/>Shipments</Link><div><span>OPERATIONS / SHIPMENT</span><h1>{s.shipment_number}</h1><p>{s.customer_name} · {s.carrier_name||'Carrier pending'}</p></div><Pill tone={s.status==='delivered'?'success':'info'}>{title(s.status)}</Pill></div>
 <div className="shipmentKpis"><Card><span>Customer revenue</span><strong>{money(s.customer_charge)}</strong></Card><Card><span>Carrier cost</span><strong>{money(actual)}</strong></Card><Card><span>Gross profit</span><strong>{money(gp)}</strong></Card><Card><span>PRO</span><strong>{s.pro_number||'—'}</strong></Card></div>
 <div className="shipmentDetailGrid"><div><Card className="shipmentSection"><div className="sectionHead"><div><h3>Lane & schedule</h3><p>Operational origin, destination and service dates.</p></div></div><div className="laneDetail"><div><MapPin/><span>Origin</span><b>{s.origin?.address1||'—'}</b><p>{s.origin?.city}, {s.origin?.state} {s.origin?.postal_code}</p></div><div className="laneArrow">→</div><div><MapPin/><span>Destination</span><b>{s.destination?.address1||'—'}</b><p>{s.destination?.city}, {s.destination?.state} {s.destination?.postal_code}</p></div></div><div className="shipmentDates"><div><Clock3/><span>Pickup</span><b>{s.pickup_date||'—'}</b></div><div><Clock3/><span>Estimated delivery</span><b>{s.estimated_delivery||'—'}</b></div><div><Clock3/><span>Delivered</span><b>{s.delivered_at?new Date(s.delivered_at).toLocaleString():'—'}</b></div></div></Card><Card className="shipmentSection"><div className="sectionHead"><div><h3>Tracking timeline</h3><p>Carrier and operational status events.</p></div></div>{s.tracking_events.length?s.tracking_events.map(e=><div className="trackingRow" key={e.id}><i/><div><b>{e.status}</b><span>{e.location||'Location not supplied'} · {new Date(e.event_time).toLocaleString()}</span><p>{e.description}</p></div></div>):<div className="dashboardEmpty"><Truck/><div><b>No tracking events yet</b><span>Tracking updates will appear here as carrier connectivity is added.</span></div></div>}</Card></div><div><Card className="shipmentSection"><div className="sectionHead"><div><h3>Shipment record</h3></div></div><div className="recordRows"><div><span>Customer</span><b>{s.customer_name}</b></div><div><span>Carrier</span><b>{s.carrier_name||'—'} {s.carrier_scac&&`(${s.carrier_scac})`}</b></div><div><span>BOL</span><b>{s.bol_number||'—'}</b></div><div><span>Created</span><b>{new Date(s.created_at).toLocaleString()}</b></div></div></Card><Card className="shipmentSection"><div className="sectionHead"><div><h3>Financial audit</h3></div></div><div className="recordRows"><div><span>Quoted carrier cost</span><b>{money(s.carrier_cost)}</b></div><div><span>Final carrier cost</span><b>{s.final_carrier_cost==null?'Pending':money(s.final_carrier_cost)}</b></div><div><span>Customer charge</span><b>{money(s.customer_charge)}</b></div><div><span>Gross profit</span><b>{money(gp)}</b></div></div></Card></div></div>
 </>}
